### ISSUE TITLE
No interaction with other plugins?

### ISSUE THREAD

**Issue by thecookingsenpai** [innightwolfsleep/text-generation-webui-telegram_bot#112]
I use a nice plugin called complex_memory that uses a dynamic list of memories prepending them to the generation input. It all works on the webui (i tested a basic memory question) but it looks like in the Telegram bot the text generation skip the plugin completely (the bot does not remember things that were in the memory on the webui)

**Comment by innightwolfsleep** [comment]
No, telegram_bot works in "standalone" mode. This cased because of making separated history for telegram users, extended by message id for bot. Cant integrate this in original oobaboogacode without major changes. Also, text-generation-webui developing fast, so deeper integration means too often changes for telegram_bot.

**Comment by thecookingsenpai** [comment]
> No, telegram_bot works in "standalone" mode. This cased because of making separated history for telegram users, extended by message id for bot. Cant integrate this in original oobaboogacode without major changes. Also, text-generation-webui developing fast, so deeper integration means too often changes for telegram_bot.

Ok agreed, i'll do it on my own fork :) Great job by the way!
